### PR TITLE
Update repo cache when installing packages

### LINKED ISSUE #219: Can
**Describe the bug**
Failed to install lsb-release, apt-transport-https and gpg packages

```
TASK [nusenu.relayor : Ensure lsb-release, apt-transport-https and gpg packages are installed] *************************************************************
fatal: [root@51.158.191.33]: FAILED! => {"cache_update_time": 1618928312, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'apt-transport-https'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/a/apt/apt-transport-https_2.0.5_all.deb  404  Not Found [IP: 2001:67c:1360:8001::24 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "rc": 100, "stderr": "E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/a/apt/apt-transport-https_2.0.5_all.deb  404  Not Found [IP: 2001:67c:1360:8001::24 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stderr_lines": ["E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/a/apt/apt-transport-https_2.0.5_all.deb  404  Not Found [IP: 2001:67c:1360:8001::24 80]", "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following NEW packages will be installed:\n  apt-transport-https\n0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.\nNeed to get 1704 B of archives.\nAfter this operation, 161 kB of additional disk space will be used.\nErr:1 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 apt-transport-https all 2.0.5\n  404  Not Found [IP: 2001:67c:1360:8001::24 80]\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following NEW packages will be installed:", "  apt-transport-https", "0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.", "Need to get 1704 B of archives.", "After this operation, 161 kB of additional disk space will be used.", "Err:1 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 apt-transport-https all 2.0.5", "  404  Not Found [IP: 2001:67c:1360:8001::24 80]"]}
```

**To Reproduce**
1. Create a new stardust instance with Ubuntu 20.04 on Scaleway
2. Run the playbook

**Expected behavior**
The tor instance setup successfully

**Debug information**
I login to the instance with SSH, and run `apt-get update` to update the repo list, then I rerun the playbook and the run successes.

Maybe we should run `apt update` once before we install anything

### PR DESCRIPTION
**Pull request by tsekityam**
Fix #219

### CODE REVIEW

**Comment by nusenu** [comment]
thanks for this submission.

what do you think about adding
cache_valid_time with one day?

so that the cache is not updated everytime - which is probably not needed.

**Comment by tsekityam** [comment]
PR updated, with `cache_valid_time: 86400`

**Comment by nusenu** [comment]
thank you

**Comment by nusenu** [comment]
turns out this significantly increases our kitchen runs, so we want to add a var to make this opt-out configurable

**Comment by nusenu** [comment]
done in 9ba4d88a7b7090a7992875cdcbb7ae1a313ac8cb

**Pull request closed without merging**
