### PR TITLE
Add Travis CI config with ansible-lint check

### PR DESCRIPTION
**Pull request by Lirt**
This PR adds simple Travis CI with `ansible-lint` command.

In order to make Travis work, you need to integrate Travis with this project, enable CI for this project in Travis and repush commit (or try to force build this PR in Travis) to trigger build.

### CODE REVIEW

**Comment by nusenu** [comment]
Thanks for this.
Do they still require write access to the repository?

**Comment by Lirt** [comment]
According to Issue discussion and Forum thread the travis-ci.org has this issue fixed, but travis-ci.com not. But they are working also on `.com` version.

If you try to authenticate, it should show you all permissions it asks. I am already integrated and don't want to break all my stuff with testing. 

Here are resources:

* https://docs.travis-ci.com/user/github-oauth-scopes/#travis-ci-for-open-source-projects
* https://github.com/travis-ci/travis-ci/issues/1390
* https://travis-ci.community/t/is-there-a-plan-to-stop-travis-requesting-read-write-access-on-travis-ci-com-login/1364/3

**Comment by nusenu** [comment]
unless we find a way to implement the "have at least that much somaxconn/nmbclusters but don't change it if it is already higher than the minimal acceptable value" logic
https://github.com/nusenu/ansible-relayor/blob/master/tasks/freebsd_prepare.yml#L29

we probably want to disable the check 306 

I havn't looked into the 506 failure.

Once ansible-lint is no longer expected to fail I'll merge this.

**Comment by Lirt** [comment]
Check 306 seems reasonable, but you can do it more simply without piping.

* `sysctl -n kern.ipc.somaxconn`.
* `sysctl -n kern.ipc.nmbclusters`.
* `sysctl -n kern.maxfiles`.

**Comment by nusenu** [comment]
merged

**Pull request closed without merging**
