### PR TITLE
In accord with dpkg-statoverride manual, remove then add

### PR DESCRIPTION
**Pull request by Tuuux**
Signed-off-by: Tuux <tuxa@rtnp.org>

### CODE REVIEW

**Comment by nusenu** [comment]
Tuuux:
> Signed-off-by: Tuux <tuxa@rtnp.org>
> You can view, comment on, or merge this pull request online at:

Hi Tuuux,

thanks for submitting a pull request and sorry for the long response
time. Can you elaborate on the motivation of this change? Does the role
fail for you without that change?

thanks,
nusenu

**Comment by Tuuux** [comment]
Hello,

Sorry for the delay,

Yes it crash on Debian , when i have search the root cause.
It's due that because "add" return a error when the key is all ready here.

Unfortunally i have remove "become: yes" for sta-y compatible with you role.

Regards
---
Tuux

**Comment by nusenu** [comment]
Hello Tuux,
thanks for reporting back! Could you provide more information on what you mean exactly by "crash".
Does the playbook run abort at that task?
Can you please provide a playbook run output, the debian version of the target and the ansible version?

Note: the task fails most of the time (except the first time) but the task failure is expected and that is the reason for having:
```ignore_errors: yes ```

**Comment by nusenu** [comment]
@Tuuux ping

**Comment by nusenu** [comment]
user disappeared

**Pull request closed without merging**
